branches:
  only:
  - main
  - performanceboosts
language: node_js
node_js:
  - 14.15.5
services:
  - docker
jobs:
  include:
    - stage: build and push to docker
      script:
        - npm run build-prod
        - docker build -t localoverview .
        - docker tag localoverview:latest kimberlyjk/overview
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push kimberlyjk/overview