version: "3"
services:
  app:
    container_name: overview
    image: kimberlyjk/overview
    restart: always
    build: .
    ports:
      - "3003:3003"
    links:
       - mango_fec
    depends_on:
      - mango_fec
  mango_fec:
    container_name: mango_fec
    image: mongo
    volumes:
      - /dockerApp/data/db
    ports:
      - "27017:27017"