version: "3.9"  # optional since v1.27.0
services:
  web:
    image: node:14.15.5
    ports:
      - "3003:3003"
    depends_on:
    - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081